### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by lrj231** [kirklin/brics-skills-iot-screen#1]
### Describe the bug

为啥run dev后网页中没有内容

### Reproduction

求解

### System Info

```Shell
就是内容为空
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/kirklin/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/kirklin/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
Thank you for your reminder. If you are experiencing an issue, providing more information can help us better understand your problem and give a more accurate solution.

This information can include:

The package manager you are using: such as npm, yarn, pnpm etc.
The operating system and version: such as Windows 10, macOS 11, Ubuntu 20.04, etc.
The version of the program: if you are using a software or library, please provide its version information
Screenshots of error messages: if you see an error message, please take a screenshot and provide it
Console output: if you see some output, please provide screenshots or text of the output
Solutions you have tried: if you have tried some solutions, please provide details
This information can help us better understand your problem and give helpful suggestions as soon as possible.
